

version: '3.5'

services:
  app:
    image: quarkus/backend-jvm:latest
    container_name: quarkus-app
    environment:
      - JAVA_OPTIONS=-Xmx1000m
      - BATCH_SIZE=100
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/my_db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=root

    ports:
      - "8080:8080"
    networks:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2000M
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    container_name: postgres_container_batch
    image: postgres:15.3-alpine
    mem_limit: 512MiB
    cpus: 0.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: my_db
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_batch
    image: dpage/pgadmin4:latest
    mem_limit: 512MiB
    cpus: 0.5
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./share:/home
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
